@url_dev=http://localhost:3055/v1/api

### signup

POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 8657037a9e54c8e0b20e73b1e50a37d25a5349614eff5bf214cd5396dfef15c730b9c9ecfd5747e58f2e099e30e49175d5d4299dc89effa58c479bbaaaefa9b6

{
  "name": "Shop Tri",
  "password": "abc123",
  "email": "trirectelework1@gmail.com"
}